//! Plain-text feed tick file: the `sim -> d1` scenario-transport seam.
//!
//! Format: one header block of `#`-prefixed comment lines (ignored
//! anywhere in the file, not just at the top), then one space-separated
//! data line per tick:
//!
//! ```text
//! # d1 tick file v1 -- generated by `sim --mode emit-ticks`; do not hand-edit
//! # scenario: tracker-flow  seed: 42
//! # instrument_id bid_px_e9 ask_px_e9 last_px_e9 exch_ts_ns div_per_share_e9
//! 1001 187500000000 187520000000 187510000000 0 0
//! ```
//!
//! This is the output of `sim --mode emit-ticks` (`crates/sim/src/emit.rs`)
//! and the input to [`load`], which `crates/d1/src/main.rs` feeds into
//! `d1::spawn`'s `feed_ticks` parameter in place of `feed.rs`'s synthetic
//! random walk.
//!
//! Plain text over JSON/CSV/binary: zero new dependencies (the hard
//! constraint on this transport -- no serde on `d1-core`'s wire-adjacent
//! types, `sim/CLAUDE.md`'s sim -> d1-core-only dependency direction), an
//! exact integer round-trip (no float reparsing of an already-fixed-point
//! value), a git-diffable artifact if one ever needed to be committed (it
//! deliberately isn't, see `justfile`'s `d1-scenario` recipe), and a parser
//! that is naturally free of `[]` indexing (`indexing_slicing` is
//! deny-level in this workspace) since whitespace-splitting plus typed
//! `parse()` calls never need a index into a fixed-width row.

use std::path::Path;

use anyhow::{Context, Result};
use d1_core::{FeedTick, InstrumentId};

use crate::feed;

/// Read and parse the tick file at `path`. See module docs for the format.
pub fn load(path: &Path) -> Result<Vec<FeedTick>> {
    let text = std::fs::read_to_string(path)
        .with_context(|| format!("reading feed tick file at {}", path.display()))?;
    parse(&text).with_context(|| format!("parsing feed tick file at {}", path.display()))
}

/// Parse tick-file text into an ordered `Vec<FeedTick>`. Pure (no I/O), so
/// it is unit-testable directly. See module docs for the format.
pub fn parse(text: &str) -> Result<Vec<FeedTick>> {
    let mut ticks = Vec::new();
    let mut prev_exch_ts_ns: Option<u64> = None;

    for (idx, line) in text.lines().enumerate() {
        let n = idx + 1; // 1-indexed line number for error messages
        let trimmed = line.trim();
        if trimmed.is_empty() || trimmed.starts_with('#') {
            continue;
        }

        let mut fields = trimmed.split_ascii_whitespace();

        let instrument_id: u32 = fields
            .next()
            .with_context(|| format!("line {n}: missing field instrument_id"))?
            .parse()
            .with_context(|| format!("line {n}: invalid instrument_id"))?;
        let bid_px_e9: i64 = fields
            .next()
            .with_context(|| format!("line {n}: missing field bid_px_e9"))?
            .parse()
            .with_context(|| format!("line {n}: invalid bid_px_e9"))?;
        let ask_px_e9: i64 = fields
            .next()
            .with_context(|| format!("line {n}: missing field ask_px_e9"))?
            .parse()
            .with_context(|| format!("line {n}: invalid ask_px_e9"))?;
        let last_px_e9: i64 = fields
            .next()
            .with_context(|| format!("line {n}: missing field last_px_e9"))?
            .parse()
            .with_context(|| format!("line {n}: invalid last_px_e9"))?;
        let exch_ts_ns: u64 = fields
            .next()
            .with_context(|| format!("line {n}: missing field exch_ts_ns"))?
            .parse()
            .with_context(|| format!("line {n}: invalid exch_ts_ns"))?;
        let div_per_share_e9: i64 = fields
            .next()
            .with_context(|| format!("line {n}: missing field div_per_share_e9"))?
            .parse()
            .with_context(|| format!("line {n}: invalid div_per_share_e9"))?;

        anyhow::ensure!(fields.next().is_none(), "line {n}: trailing fields");

        // Non-decreasing across the whole file: `run_tick_file_producer`'s
        // pacer computes each tick's deadline as an ABSOLUTE offset from one
        // `Instant` captured at entry, so a file whose clock ever runs
        // backwards would send that deadline backwards too.
        if let Some(prev) = prev_exch_ts_ns {
            anyhow::ensure!(
                exch_ts_ns >= prev,
                "line {n}: exch_ts_ns {exch_ts_ns} is less than the previous tick's {prev} -- tick files must be non-decreasing in time"
            );
        }
        prev_exch_ts_ns = Some(exch_ts_ns);

        ticks.push(FeedTick {
            instrument_id: InstrumentId(instrument_id),
            bid_px_e9,
            ask_px_e9,
            last_px_e9,
            exch_ts_ns,
            div_per_share_e9,
        });
    }

    anyhow::ensure!(!ticks.is_empty(), "tick file has no data lines");

    Ok(ticks)
}

/// Warn, to stderr, about two coverage mismatches between `ticks` and
/// `universe`: (1) `ticks` covers only a strict subset of `universe`'s
/// instruments, and (2) `ticks` names instrument ids outside `universe`
/// entirely -- `MarketData::ingest` (`run_core`'s consumer) returns `false`
/// and silently drops those, so this is the only place that names them
/// before that happens. Lives in this module (rather than `main.rs`)
/// specifically so it can read `feed::STARTING_PX_E9` -- `pub(crate)`,
/// deliberately not re-exported -- without widening `d1-core`/`d1`'s public
/// API just for a startup log line.
///
/// Deliberate minimal handling: this does NOT synthesize filler ticks for
/// uncovered instruments, and does NOT reject out-of-universe ids -- either
/// would mean inventing or discarding market data the scenario/tick file
/// explicitly specified. The warnings are the whole remediation; the
/// uncovered instruments simply keep `run_core`'s unconditional t=0 prime
/// for the rest of the session.
pub fn report_coverage(ticks: &[FeedTick], universe: &[InstrumentId]) {
    // `HashSet` built once and probed per tick, rather than a linear
    // `Vec::contains` scan per tick (O(ticks) instead of O(ticks *
    // universe.len())) -- immaterial at demo scale (a handful of ticks,
    // 15 instruments) but the universe is enriched at scale in P4.M5.
    let universe_set: std::collections::HashSet<InstrumentId> = universe.iter().copied().collect();
    let mut covered: std::collections::HashSet<InstrumentId> = std::collections::HashSet::new();
    let mut out_of_universe: std::collections::HashSet<InstrumentId> =
        std::collections::HashSet::new();
    for tick in ticks {
        if universe_set.contains(&tick.instrument_id) {
            covered.insert(tick.instrument_id);
        } else {
            out_of_universe.insert(tick.instrument_id);
        }
    }

    if covered.len() < universe.len() {
        eprintln!(
            "d1: feed tick file covers {}/{} universe instruments; the other {} hold run_core's t=0 prime of {} e9 all session -- internal crosses on them price at that prime, not a scenario price",
            covered.len(),
            universe.len(),
            universe.len() - covered.len(),
            feed::STARTING_PX_E9
        );
    }

    // The more actionable of the two warnings: an out-of-universe id is
    // silently dropped by `MarketData::ingest`, not merely left at its t=0
    // prime -- that tick's data never lands anywhere.
    if !out_of_universe.is_empty() {
        let mut ids: Vec<InstrumentId> = out_of_universe.into_iter().collect();
        ids.sort();
        const MAX_NAMED_IDS: usize = 10;
        if ids.len() <= MAX_NAMED_IDS {
            eprintln!(
                "d1: feed tick file names {} instrument id(s) outside the universe, which will be dropped on ingest: {ids:?}",
                ids.len(),
            );
        } else {
            eprintln!(
                "d1: feed tick file names {} instrument id(s) outside the universe, which will be dropped on ingest",
                ids.len(),
            );
        }
    }
}

#[cfg(test)]
// tests: unwrap_used/expect_used/indexing_slicing are hot-path-only bans
// (delta-one/CLAUDE.md); this module's assertions index fixed-length parse
// results directly rather than via `.get()`.
#[allow(clippy::unwrap_used, clippy::indexing_slicing)]
mod tests {
    use super::*;

    const HAPPY: &str = "\
# d1 tick file v1 -- generated by `sim --mode emit-ticks`; do not hand-edit
# scenario: tracker-flow  seed: 42
# instrument_id bid_px_e9 ask_px_e9 last_px_e9 exch_ts_ns div_per_share_e9
1001 187500000000 187520000000 187510000000 0 0

1001 176000000000 176000000000 176000000000 5000000000 0
1001 175750000000 175750000000 175750000000 9000000000 250000000
";

    #[test]
    fn parses_three_lines() {
        let ticks = parse(HAPPY).unwrap();
        assert_eq!(ticks.len(), 3);
        assert_eq!(
            ticks[0],
            FeedTick {
                instrument_id: InstrumentId(1001),
                bid_px_e9: 187_500_000_000,
                ask_px_e9: 187_520_000_000,
                last_px_e9: 187_510_000_000,
                exch_ts_ns: 0,
                div_per_share_e9: 0,
            }
        );
        assert_eq!(
            ticks[2],
            FeedTick {
                instrument_id: InstrumentId(1001),
                bid_px_e9: 175_750_000_000,
                ask_px_e9: 175_750_000_000,
                last_px_e9: 175_750_000_000,
                exch_ts_ns: 9_000_000_000,
                div_per_share_e9: 250_000_000,
            }
        );
    }

    #[test]
    fn skips_comments_and_blank_lines() {
        // HAPPY already has a leading comment block and one blank line
        // between ticks -- both must be skipped, not just the header.
        let ticks = parse(HAPPY).unwrap();
        assert_eq!(ticks.len(), 3);
    }

    #[test]
    fn too_few_fields_is_an_error() {
        let err = parse("1001 187500000000 187520000000\n").unwrap_err();
        assert!(format!("{err:#}").contains("line 1"));
    }

    #[test]
    fn trailing_fields_is_an_error() {
        let err = parse("1001 1 1 1 0 0 extra\n").unwrap_err();
        assert!(format!("{err:#}").contains("trailing fields"));
    }

    #[test]
    fn non_integer_field_is_an_error() {
        let err = parse("1001 187.50 187520000000 187510000000 0 0\n").unwrap_err();
        assert!(format!("{err:#}").contains("bid_px_e9"));
    }

    #[test]
    fn empty_input_is_an_error() {
        assert!(parse("").is_err());
        assert!(parse("# only a comment\n").is_err());
    }

    #[test]
    fn non_monotonic_exch_ts_ns_is_an_error() {
        let text = "1001 1 1 1 5000 0\n1001 1 1 1 1000 0\n";
        let err = parse(text).unwrap_err();
        assert!(format!("{err:#}").contains("non-decreasing"));
    }
}
