//! d1-posttrade — see delta-one/CLAUDE.md for the crate's role and rules.
//!
//! P1.M4 Slice 1: a pure Avro encoder engine. This crate defines the ring
//! payload types the core thread will eventually publish (Slice 2 wires them
//! onto `rtrb` rings and an `rdkafka` producer thread; none of that exists
//! yet) and `convert.rs`, which maps those payloads to the Avro records in
//! `protocol/avro/`. No Kafka, no threads, no rings here — off the hot path
//! per the crate table, so heap allocation, `String`, wall-clock and Avro
//! are all allowed, but the payload types themselves stay `Copy` and
//! id-based (no instrument symbol/currency string at rest): symbol/currency
//! resolve at the edge from `d1-refdata::Universe`, exactly like
//! `d1-gateway-nats::convert` resolves proto fields.

pub mod convert;

use d1_core::{BookId, ClOrdId, ExecId, InstrumentId, OrderStatus, Side};
use uuid::Uuid;

pub use convert::Schemas;

/// One post-trade event to encode. Mirrors the four Avro record types in
/// `protocol/avro/` (`posttrade_trade`, `posttrade_cross`,
/// `posttrade_allocation`, `order_audit`).
#[derive(Debug, Clone, Copy)]
pub enum PostTradeEvent {
    /// A booked trade leg (external fill or internal cross leg).
    Trade(TradeLeg),
    /// An explicit internal cross between two books (ADR-005).
    Cross(Cross),
    /// A pro-rata allocation of an external fill back to a book.
    Allocation(Allocation),
    /// An order state transition, for compliance replay.
    OrderAudit(OrderAudit),
}

/// Which side of a trade produced a `TradeLeg`: an external venue fill, or
/// one leg of an internal cross.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum TradeKind {
    /// A fill against an external venue.
    ExternalFill,
    /// One leg of an explicit internal cross (ADR-005).
    InternalCrossLeg,
}

/// Booked trade leg (topic `posttrade.trades`, key `instrument_id`). `Copy`
/// and id-based — `convert::encode` resolves `symbol`/`currency` from
/// `d1-refdata::Universe`.
#[derive(Debug, Clone, Copy)]
pub struct TradeLeg {
    /// Book this leg is booked to.
    pub book: BookId,
    /// Instrument traded.
    pub instrument: InstrumentId,
    /// Buy/sell direction.
    pub side: Side,
    /// Quantity, fixed-point x10^2.
    pub qty_e2: i64,
    /// Price, fixed-point x10^9.
    pub px_e9: i64,
    /// Whether this leg is an external fill or an internal cross leg.
    pub kind: TradeKind,
    /// Set for `InternalCrossLeg`: the cross this leg belongs to.
    pub cross_id: Option<Uuid>,
    /// Set for `ExternalFill`: the parent client order id.
    pub parent_cl_ord_id: Option<ClOrdId>,
    /// Set for `ExternalFill`: the exec id of the fill.
    pub exec_id: Option<ExecId>,
    /// "INTERNAL" for cross legs, the venue/broker id otherwise.
    pub counterparty: &'static str,
}

/// Lineage back to the netting cycle that produced a cross or allocation.
/// The Avro field is a plain string (no union): a directed-transfer cross
/// has no netting cycle, so it encodes to the sentinel `"DIRECT"` instead of
/// widening the wire schema with a nullable/union field for one case.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum NettingCycleId {
    /// Generated by netting cycle `n`; encodes as `n.to_string()`.
    Cycle(u64),
    /// A directed transfer, booked outside any netting cycle (ADR-009);
    /// encodes as the sentinel string `"DIRECT"`.
    Direct,
}

/// Explicit internal cross between two books (topic `posttrade.crosses`,
/// key `cross_id`). `Copy` and id-based.
#[derive(Debug, Clone, Copy)]
pub struct Cross {
    /// Compliance-lineage identity for this cross (matches the NATS
    /// `d1.crosses` notice's `cross_id`, `d1_core::CrossRecord`).
    pub cross_id: Uuid,
    /// Instrument crossed.
    pub instrument: InstrumentId,
    /// Book on the buy side.
    pub buy_book: BookId,
    /// Book on the sell side.
    pub sell_book: BookId,
    /// Quantity crossed, fixed-point x10^2.
    pub qty_e2: i64,
    /// Cross reference price, fixed-point x10^9.
    pub ref_px_e9: i64,
    /// Compliance-visible reference-price policy id (ADR-005 s.4).
    pub policy_id: &'static str,
    /// Netting cycle that produced this cross, or `Direct`.
    pub netting_cycle_id: NettingCycleId,
}

/// Pro-rata allocation of an external fill back to a book (topic
/// `posttrade.allocations`, key `parent_cl_ord_id`). `Copy` and id-based.
#[derive(Debug, Clone, Copy)]
pub struct Allocation {
    /// Parent (firm-level) client order id this allocation traces back to.
    pub parent_cl_ord_id: ClOrdId,
    /// Exec id of the fill being allocated.
    pub exec_id: ExecId,
    /// Instrument allocated.
    pub instrument: InstrumentId,
    /// Book this allocation is booked to.
    pub book: BookId,
    /// Quantity allocated, fixed-point x10^2.
    pub qty_e2: i64,
    /// Price, fixed-point x10^9.
    pub px_e9: i64,
    /// Netting cycle that produced this allocation, or `Direct`.
    pub netting_cycle_id: NettingCycleId,
}

/// Origin of an order state transition, for compliance replay.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum AuditOrigin {
    /// Emitted by the netting engine's own booking flow.
    NettingEngine,
    /// Triggered by a manual UI action.
    ManualUi,
    /// Any other internal system trigger.
    System,
}

/// An order state transition (topic `posttrade.orders.audit`, key
/// `cl_ord_id`). `Copy` and id-based.
#[derive(Debug, Clone, Copy)]
pub struct OrderAudit {
    /// Client order id transitioning.
    pub cl_ord_id: ClOrdId,
    /// Instrument the order trades.
    pub instrument: InstrumentId,
    /// Buy/sell direction.
    pub side: Side,
    /// Status before the transition.
    pub from_status: OrderStatus,
    /// Status after the transition.
    pub to_status: OrderStatus,
    /// Quantity of this transition's event, fixed-point x10^2.
    pub qty_e2: i64,
    /// Cumulative filled quantity, fixed-point x10^2.
    pub cum_qty_e2: i64,
    /// Remaining unfilled quantity, fixed-point x10^2.
    pub leaves_qty_e2: i64,
    /// What triggered this transition.
    pub origin: AuditOrigin,
    /// Optional free-text detail (e.g. a reject reason).
    pub detail: Option<&'static str>,
}

/// Failure modes for `d1-posttrade`.
#[derive(Debug, thiserror::Error)]
pub enum PostTradeError {
    /// A `BookId`/`InstrumentId` (`u32`) did not fit in the Avro `int`
    /// (`i32`) field it maps to.
    #[error("id {0} does not fit in an Avro `int` (i32)")]
    IdOverflow(u32),
    /// The event named an instrument not present in the loaded
    /// `d1-refdata::Universe` (no symbol/currency to resolve).
    #[error("instrument {0:?} not found in refdata universe")]
    UnknownInstrument(InstrumentId),
    /// The system clock is set before the Unix epoch.
    #[error("system clock is before the Unix epoch")]
    ClockBeforeEpoch(#[source] std::time::SystemTimeError),
    /// Avro schema parse or encode failure.
    #[error(transparent)]
    Avro(#[from] apache_avro::Error),
}
