//! Expands a scenario timeline into a plain-text feed tick file
//! (`d1::tickfile`'s format) that `d1 --feed-ticks <path>` replays into the
//! live feed ring -- the transport that lets the flagship `tracker-flow`
//! scenario drive a real `d1` process instead of `replay.rs`'s throwaway
//! in-process `MarketData` table. `sim/CLAUDE.md`: no sim code may be
//! imported by production crates, dependency direction is sim -> d1-core
//! only, so this writes a file rather than calling into `d1` directly.
//!
//! Known divergence, deliberately not converged here: `sim replay` credits
//! a `dividend` action's cash with NO accompanying ex-div price move (its
//! `MarketData` entry keeps whatever mid it last had), while `expand`'s
//! dividend arm below emits an ex-div tick -- the price drops by the
//! dividend amount on the same tick that carries the credit, same
//! rationale as `crates/d1/src/feed.rs::run_feed_producer`'s M6
//! remediation: crediting cash without dropping the price creates value out
//! of nothing, and `run_core` (the eventual consumer of this file) credits
//! dividends from `FeedTick::div_per_share_e9` and nowhere else, so a
//! keeper-side-only credit has no representation on this transport at all.
//! Same YAML `action: dividend`, two different readings depending on which
//! binary mode consumes it. Converging them would change `just sim`'s
//! printed AAPL row from 176.00 to 175.75 -- a P1.M5 tracker-output
//! behavior change, out of scope for this transport-only change and
//! recorded as a P2.M4 debt item (`docs/PONYTAIL-DEBT.md`).

use std::collections::{BTreeMap, HashMap};
use std::path::Path;

use anyhow::{Context, Result, bail};
use d1_core::{FeedTick, InstrumentId};
use d1_refdata::Universe;

use crate::replay::{resolve, to_fixed_e9};
use crate::scenario::{self, Scenario};

/// Load `scenario_path`, expand its timeline into a tick file, and write it
/// to `out_path` (creating parent directories as needed). Loads the
/// scenario/universe the same way `replay::run` does.
pub fn run(scenario_path: &Path, out_path: &Path) -> Result<()> {
    let scenario = scenario::load(scenario_path)
        .with_context(|| format!("loading scenario {}", scenario_path.display()))?;

    let scenario_dir = scenario_path.parent().unwrap_or_else(|| Path::new("."));
    let universe_path = scenario_dir.join(&scenario.universe);
    let universe = d1_refdata::load(&universe_path)?;

    let (ticks, skipped) = expand(&scenario, &universe)?;
    print_skip_summary(ticks.len(), &skipped);

    if let Some(parent) = out_path.parent() {
        if !parent.as_os_str().is_empty() {
            std::fs::create_dir_all(parent)
                .with_context(|| format!("creating directory {}", parent.display()))?;
        }
    }

    let mut out = String::new();
    out.push_str("# d1 tick file v1 -- generated by `sim --mode emit-ticks`; do not hand-edit\n");
    out.push_str(&format!(
        "# scenario: {}  seed: {}\n",
        scenario.scenario, scenario.seed
    ));
    out.push_str("# instrument_id bid_px_e9 ask_px_e9 last_px_e9 exch_ts_ns div_per_share_e9\n");
    for tick in &ticks {
        out.push_str(&format!(
            "{} {} {} {} {} {}\n",
            tick.instrument_id.0,
            tick.bid_px_e9,
            tick.ask_px_e9,
            tick.last_px_e9,
            tick.exch_ts_ns,
            tick.div_per_share_e9,
        ));
    }

    std::fs::write(out_path, out)
        .with_context(|| format!("writing tick file to {}", out_path.display()))?;

    Ok(())
}

/// Expand a scenario's timeline into an ordered `FeedTick` sequence, plus a
/// tally of skipped non-feed entries by action label (`run` above turns that
/// tally into the one-line stderr summary via `print_skip_summary` -- kept
/// out of this function so it stays pure: no I/O, directly unit-testable).
/// Mirrors `replay::run`'s `quote`/`gap` arms verbatim (same `to_fixed_e9`,
/// same `resolve`, same `bail!` wording for missing fields); `dividend`
/// diverges as described in this module's doc comment.
fn expand(
    scenario: &Scenario,
    universe: &Universe,
) -> Result<(Vec<FeedTick>, BTreeMap<String, usize>)> {
    // Last-known-price store, tracked explicitly rather than reusing
    // `d1_core::MarketData` as a quote cache: `MarketData::quote`'s
    // `exch_ts_ns == 0` means "never ticked", but `entry.at_ms * 1_000_000`
    // legitimately produces `exch_ts_ns == 0` too, for any `quote`/`gap` at
    // `at_ms: 0` -- the two are indistinguishable through that API, so a
    // real t=0 quote would be misread as "no prior quote" by the dividend
    // arm below. An explicit map keyed on the last emitted price sidesteps
    // the ambiguity entirely.
    let mut last_px_e9: HashMap<InstrumentId, i64> = HashMap::new();
    let mut ticks = Vec::new();
    // Tally of skipped non-feed entries, keyed by action label (or
    // "expect" for assertion entries with no `action`), for the one-line
    // stderr summary below -- built from what was ACTUALLY skipped, never
    // hardcoded.
    let mut skipped: BTreeMap<String, usize> = BTreeMap::new();

    for entry in &scenario.timeline {
        let Some(action) = entry.action.as_deref() else {
            *skipped.entry("expect".to_string()).or_insert(0) += 1;
            continue;
        };
        match action {
            "quote" => {
                let (Some(symbol), Some(bid), Some(ask)) =
                    (&entry.instrument, entry.bid, entry.ask)
                else {
                    bail!("quote at {}ms missing instrument/bid/ask", entry.at_ms);
                };
                let id = resolve(universe, symbol, entry.at_ms)?;
                let bid_px_e9 = to_fixed_e9(bid);
                let ask_px_e9 = to_fixed_e9(ask);
                // `checked_add`, not `+`: `serde_yaml` accepts YAML-1.1
                // `.inf`, and `to_fixed_e9`'s `f64 as i64` cast saturates
                // rather than panicking, so a quote with `bid`/`ask: .inf`
                // turns `bid_px_e9`/`ask_px_e9` into `i64::MAX` --
                // `bid_px_e9 + ask_px_e9` then overflows `i64`.
                // `[profile.release]` has `overflow-checks` off, so an
                // unchecked add would silently wrap into a bogus price that
                // `d1` then books as real (root CLAUDE.md invariant 1).
                let Some(mid_sum_e9) = bid_px_e9.checked_add(ask_px_e9) else {
                    bail!(
                        "quote at {}ms instrument={:?}: bid_px_e9={} plus ask_px_e9={} overflows i64",
                        entry.at_ms,
                        id,
                        bid_px_e9,
                        ask_px_e9
                    );
                };
                let tick = FeedTick {
                    instrument_id: id,
                    bid_px_e9,
                    ask_px_e9,
                    last_px_e9: mid_sum_e9 / 2,
                    exch_ts_ns: ns_from_at_ms(entry.at_ms)?,
                    div_per_share_e9: 0,
                };
                last_px_e9.insert(id, tick.last_px_e9);
                ticks.push(tick);
            }
            "gap" => {
                let (Some(symbol), Some(to_mid)) = (&entry.instrument, entry.to_mid) else {
                    bail!("gap at {}ms missing instrument/to_mid", entry.at_ms);
                };
                let id = resolve(universe, symbol, entry.at_ms)?;
                let px_e9 = to_fixed_e9(to_mid);
                let tick = FeedTick {
                    instrument_id: id,
                    bid_px_e9: px_e9,
                    ask_px_e9: px_e9,
                    last_px_e9: px_e9,
                    exch_ts_ns: ns_from_at_ms(entry.at_ms)?,
                    div_per_share_e9: 0,
                };
                last_px_e9.insert(id, tick.last_px_e9);
                ticks.push(tick);
            }
            "dividend" => {
                let (Some(symbol), Some(amount)) = (&entry.instrument, entry.amount_per_share)
                else {
                    bail!(
                        "dividend at {}ms missing instrument/amount_per_share",
                        entry.at_ms
                    );
                };
                let id = resolve(universe, symbol, entry.at_ms)?;
                let div_per_share_e9 = to_fixed_e9(amount);
                // Ex-div drop (module doc comment): the emitted tick's
                // price is the instrument's last known price minus the
                // dividend, on all three of bid/ask/last. A missing prior
                // price means there is no price to drop from, so this
                // instrument's dividend cannot be represented on the
                // tick-file transport at all -- fail loud rather than emit
                // a nonsensical `0 - div` tick.
                let Some(&prior_last_px_e9) = last_px_e9.get(&id) else {
                    bail!(
                        "dividend at {}ms instrument={:?}: no prior quote to apply the ex-div drop to",
                        entry.at_ms,
                        id
                    );
                };
                // `checked_sub`, not `-`: `serde_yaml` accepts YAML-1.1
                // `.inf`, and `to_fixed_e9`'s `f64 as i64` cast saturates
                // rather than panicking, so `amount_per_share: -.inf` turns
                // `div_per_share_e9` into `i64::MIN` -- `prior - i64::MIN`
                // then overflows `i64`. `[profile.release]` has
                // `overflow-checks` off, so an unchecked subtract would
                // silently wrap into a bogus price that `d1` then books as
                // real (root CLAUDE.md invariant 1).
                let Some(px_e9) = prior_last_px_e9.checked_sub(div_per_share_e9) else {
                    bail!(
                        "dividend at {}ms instrument={:?}: prior_last_px_e9={} minus div_per_share_e9={} overflows i64",
                        entry.at_ms,
                        id,
                        prior_last_px_e9,
                        div_per_share_e9
                    );
                };
                let tick = FeedTick {
                    instrument_id: id,
                    bid_px_e9: px_e9,
                    ask_px_e9: px_e9,
                    last_px_e9: px_e9,
                    exch_ts_ns: ns_from_at_ms(entry.at_ms)?,
                    div_per_share_e9,
                };
                last_px_e9.insert(id, tick.last_px_e9);
                ticks.push(tick);
            }
            // exo_book_event / anything else: no feed representation,
            // exactly as `replay.rs` skips them.
            other => {
                *skipped.entry(other.to_string()).or_insert(0) += 1;
            }
        }
    }

    Ok((ticks, skipped))
}

/// `at_ms * 1_000_000` (milliseconds -> `exch_ts_ns` nanoseconds), checked:
/// a malformed or hostile scenario YAML can supply an arbitrarily large
/// `at_ms`, and `[profile.release]` leaves `overflow-checks` off, so an
/// unchecked multiply would silently wrap into a bogus timestamp that `d1`
/// then treats as real (root CLAUDE.md invariant 1).
fn ns_from_at_ms(at_ms: u64) -> Result<u64> {
    let Some(ns) = at_ms.checked_mul(1_000_000) else {
        bail!("at_ms {at_ms} overflows exch_ts_ns (at_ms * 1_000_000)");
    };
    Ok(ns)
}

/// Print the one-line stderr skip summary `expand` used to print itself
/// before this became a genuinely pure (no I/O) function -- callers that
/// want the log line call this after `expand` returns. Built from what was
/// ACTUALLY skipped (`skipped`), never hardcoded.
fn print_skip_summary(emitted: usize, skipped: &BTreeMap<String, usize>) {
    let skipped_total: usize = skipped.values().sum();
    let skipped_detail = skipped
        .iter()
        .map(|(action, count)| {
            if *count == 1 {
                action.clone()
            } else {
                format!("{action} x{count}")
            }
        })
        .collect::<Vec<_>>()
        .join(", ");
    eprintln!(
        "sim: emitted {emitted} ticks, skipped {skipped_total} non-feed timeline entries ({skipped_detail})",
    );
}

#[cfg(test)]
// tests: unwrap_used/expect_used/indexing_slicing are hot-path-only bans
// (delta-one/CLAUDE.md); this module's assertions unwrap `expand`'s result
// and index its fixed-length tick vec directly, same carve-out shape as
// `crates/d1/src/config.rs`'s and `crates/d1/src/tickfile.rs`'s test modules.
#[allow(clippy::unwrap_used, clippy::indexing_slicing)]
mod tests {
    use super::*;
    use crate::scenario::TimelineEntry;

    /// Minimal one-instrument `Universe`, hand-built rather than loaded from
    /// `protocol/refdata/universe.json` from disk -- every field is `pub`
    /// (`d1-refdata::Universe`), so a direct struct literal is simpler than
    /// parsing YAML/JSON just to exercise `expand`'s pure logic.
    fn test_universe() -> Universe {
        let id = InstrumentId(1001);
        Universe {
            book_ids: Vec::new(),
            instrument_ids: vec![id],
            tracker_books: Vec::new(),
            cash_yield_annual_e9: 0,
            symbol_to_id: HashMap::from([("AAPL".to_string(), id)]),
            id_to_symbol: HashMap::from([(id, "AAPL".to_string())]),
            id_to_currency: HashMap::from([(id, "USD".to_string())]),
            cross_px_policy: "ARRIVAL_MID".to_string(),
            venue_counterparty: "SIM".to_string(),
        }
    }

    fn quote_entry(at_ms: u64, symbol: &str, bid: f64, ask: f64) -> TimelineEntry {
        TimelineEntry {
            at_ms,
            action: Some("quote".to_string()),
            instrument: Some(symbol.to_string()),
            bid: Some(bid),
            ask: Some(ask),
            to_mid: None,
            amount_per_share: None,
        }
    }

    fn dividend_entry(at_ms: u64, symbol: &str, amount_per_share: f64) -> TimelineEntry {
        TimelineEntry {
            at_ms,
            action: Some("dividend".to_string()),
            instrument: Some(symbol.to_string()),
            bid: None,
            ask: None,
            to_mid: None,
            amount_per_share: Some(amount_per_share),
        }
    }

    /// Regression test for the bug this FIX addresses: a `quote` at
    /// `at_ms: 0` legitimately produces `exch_ts_ns == 0`, which used to be
    /// indistinguishable from `d1_core::MarketData::quote`'s "never ticked"
    /// sentinel -- `expand` must accept the t=0 quote as a valid prior price
    /// for the dividend that follows, not reject it as "no prior quote".
    #[test]
    fn dividend_after_a_t0_quote_uses_that_quote_as_the_prior_price() {
        let scenario = Scenario {
            scenario: "t0-dividend".to_string(),
            seed: 1,
            universe: "universe.json".to_string(),
            timeline: vec![
                quote_entry(0, "AAPL", 187.50, 187.52),
                dividend_entry(9_000, "AAPL", 0.25),
            ],
        };

        let (ticks, skipped) = expand(&scenario, &test_universe()).unwrap();
        assert!(skipped.is_empty());
        assert_eq!(ticks.len(), 2);

        let quote_tick = ticks[0];
        assert_eq!(quote_tick.exch_ts_ns, 0);
        assert_eq!(quote_tick.last_px_e9, 187_510_000_000);

        // Ex-div drop: 187.51 (the t=0 quote's mid) - 0.25 = 187.26.
        let dividend_tick = ticks[1];
        assert_eq!(dividend_tick.exch_ts_ns, 9_000_000_000);
        assert_eq!(dividend_tick.last_px_e9, 187_260_000_000);
        assert_eq!(dividend_tick.bid_px_e9, 187_260_000_000);
        assert_eq!(dividend_tick.ask_px_e9, 187_260_000_000);
        assert_eq!(dividend_tick.div_per_share_e9, 250_000_000);
    }

    #[test]
    fn dividend_with_no_prior_quote_at_all_still_errors() {
        let scenario = Scenario {
            scenario: "no-prior-quote".to_string(),
            seed: 1,
            universe: "universe.json".to_string(),
            timeline: vec![dividend_entry(9_000, "AAPL", 0.25)],
        };

        let err = expand(&scenario, &test_universe()).unwrap_err();
        assert!(format!("{err:#}").contains("no prior quote"));
    }

    #[test]
    fn dividend_overflow_is_a_checked_error_not_a_wrapped_price() {
        // `.inf` parses through `serde_yaml`/`f64`, and `to_fixed_e9`'s
        // `as i64` cast saturates it to `i64::MIN` -- `prior - i64::MIN`
        // must be rejected via `checked_sub`, not silently wrapped.
        let scenario = Scenario {
            scenario: "overflow-dividend".to_string(),
            seed: 1,
            universe: "universe.json".to_string(),
            timeline: vec![
                quote_entry(0, "AAPL", 187.50, 187.52),
                dividend_entry(9_000, "AAPL", f64::NEG_INFINITY),
            ],
        };

        let err = expand(&scenario, &test_universe()).unwrap_err();
        assert!(format!("{err:#}").contains("overflows"));
    }

    #[test]
    fn quote_mid_overflow_is_a_checked_error_not_a_wrapped_price() {
        // `.inf` parses through `serde_yaml`/`f64`, and `to_fixed_e9`'s
        // `as i64` cast saturates it to `i64::MAX` -- `bid_px_e9 +
        // ask_px_e9` must be rejected via `checked_add`, not silently
        // wrapped.
        let scenario = Scenario {
            scenario: "overflow-quote".to_string(),
            seed: 1,
            universe: "universe.json".to_string(),
            timeline: vec![quote_entry(0, "AAPL", f64::INFINITY, f64::INFINITY)],
        };

        let err = expand(&scenario, &test_universe()).unwrap_err();
        assert!(format!("{err:#}").contains("overflows"));
    }
}
